/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.tennis

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test


class TennisScoreBoardShould {
    @Test
    fun `the board empty when the game has started`() {
        val board = TennisScoreBoard()

        assertThat(board.showResult()).isEqualTo("")
    }

    @Test
    fun `show the message "love-All" when the score is 0-0`() {
        val board = TennisScoreBoard()

        board.setScore(0,0)

        assertThat(board.showResult()).isEqualTo("Love-All")
    }
}