/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.tennis

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test


class TennisScoreBoardShould {
    @Test
    fun `the board empty when the game has started`() {
        val board = TennisScoreBoard()

        assertThat(board.showResult()).isEqualTo("")
    }
}